apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.imageVectorOverwrite }}
      annotations:
        checksum/configmap-extension-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      priorityClassName: gardener-extension-{{ .Values.serviceName }}
      serviceAccountName: gardener-extension-{{ .Values.serviceName }}
      containers:
      - name: gardener-extension-{{ .Values.serviceName }}
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-shoot-dns-service
        - --lifecycle-max-concurrent-reconciles={{ .Values.controllers.lifecycle.concurrentSyncs }}
        - --healthcheck-max-concurrent-reconciles={{ .Values.controllers.healthcheck.concurrentSyncs }}
        - --replication-max-concurrent-reconciles={{ .Values.controllers.replication.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --leader-election-id={{ include "leaderelectionid" . }}
        - --leader-election-resource-lock={{ .Values.leaderElection.resourceLock }}
        - --seed-id={{ .Values.gardener.seed.identity }}
        - --dns-class={{ .Values.dnsClass }}
        {{- if .Values.dnsProviderManagement.enabled }}
        - --manage-dns-providers
        {{- end }}
        {{- if .Values.dnsProviderReplication.enabled }}
        - --replicate-dns-providers
        {{- end }}
        {{- if .Values.ownerDnsActivation.enabled }}
        - --enable-owner-dns-activation
        {{- end }}
        {{- if .Values.gardener.version }}
        - --gardener-version={{ .Values.gardener.version }}
        {{- end }}
        {{- if .Values.remoteDefaultDomainSecret.enabled }}
        - --remote-default-domain-secret={{ .Release.Namespace }}/remote-default-domain
        {{- end }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        {{- end }}
        {{- if .Values.imageVectorOverwrite }}
        volumeMounts:
        - name: extension-imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
      volumes:
      - name: extension-imagevector-overwrite
        configMap:
          name: gardener-extension-{{ .Values.serviceName }}-imagevector-overwrite
          defaultMode: 420
        {{- end }}
