{{- if .Values.remoteDefaultDomainSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-default-domain
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ toYaml .Values.remoteDefaultDomainSecret.data | trim | indent 2 }}
{{- end }}